language: python
env:
  global:
    - WORK_DIR=/home/travis/build/vespa-engine/pyvespa
    - PYVESPA_VERSION=0.2
services:
- docker
before_install:
- docker pull vespaengine/vespa
install:
- pip install -e .
jobs:
  include:
    - stage: test
      script:
      - pytest
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        username: "__token__"
        password:
          secure: 5NYbAxJn9tYlRcs4rKixcBjuFi06UQNQYcs08VtWeLhMO470kpy9ff5qVTEWrwiRYv5ct+Z5i6qlW1ALoVIk5pbGKaO0Xlt0qGpn6kXClZlPSvWTurI0IS4Cs1bCALKoA+ezJTGcE0caKYUvwFkTZCnhnpVX0D3/Rxtvj+jwqzDyamlCZ6snleDuYuTbyahBvYTiItjVFHXP50OcXaQb4Mce5IlVufD4B8LaQLtxqBMWHWF5Xx09YTaKPRfGn+NJd49LIIH8yYtEA+nGEv8gk232Y8qIhnE7iJMMPt8iIODeNFTia9XjRISP3GjC4rTm+cgYL8iWFGXhHTL5I3YwDH4O2YffecNsa90ckA+uJIYwGwElA0tdnqrzH/Gpr5Ifk6EgIjxn36iGBbO/fXiJrzpVX7EIQSvHOD0XyVYGyKvydB5Ch1mPKBmyBzh+4B1x0KP9i4hJnPU6+WrVYirOx1Q7yeaS7zAwLAcxo+glemxnlrTuhytkKoRgKfGbnWtLAJEW7o+/YJPCl/nak57pig91ZVzndO5NfNIcEHsG684J6Mug3p+9sG8RqSykTCchUF8QteSRRWoYFeYFZmLSj2C0GaMCAPkPddyzfR4xPJA9jwQYVLFtCq7jCaaS5dBxRb+gkidw6v9DhCiT1HeCyn08eOZWWiWihWu/c5b2Il4=
        on:
          all_branches: true
    - stage: retrieve
      script:
          - pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -Iv pyvespa==$PYVESPA_VERSION.$TRAVIS_JOB_NUMBER

