language: python
env:
  global:
    - WORK_DIR=/home/travis/build/vespa-engine/pyvespa
    - PYVESPA_VERSION=0.2
services:
- docker
before_install:
- docker pull vespaengine/vespa
jobs:
  include:
    - stage: test
      script:
      - pip install -e .
      - pytest
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        username: "__token__"
        password: $TEST_PYPI_TOKEN
        on:
          all_branches: true
          type: push
    - stage: retrieve
      script:
          - pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -Iv pyvespa==$PYVESPA_VERSION.$TRAVIS_BUILD_NUMBER
          - pytest
      if: type = push

