language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - WORK_DIR=/home/travis/build/vespa-engine/pyvespa
services:
  - docker
before_install:
- docker pull vespaengine/vespa
install:
  - pip install -e .
script:
  - pytest