name: pyvespa documentation search feed
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Sphinx
      run: |
        sudo apt-get install -y python3-sphinx pandoc
        python3 -m pip install -r docs/sphinx/source/requirements.txt

    - name: Build site
      run: |
        sphinx-build -E -b html docs/sphinx/source docs/sphinx/build
        find docs/sphinx/build/ -name \*.html | while read f; do (echo -e "---\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done
        bundle exec jekyll build -s docs/sphinx/build/ -p _plugins-vespafeed --config _config.yml

    - name: Feed site
      env:
        DATA_PLANE_PUBLIC_KEY : ${{ secrets.VESPA_TEAM_DATA_PLANE_PUBLIC_CERT }}
        DATA_PLANE_PRIVATE_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PRIVATE_KEY }}
      run: |
        python3 -m pip install PyYAML
        ./feed_to_vespa.py
