name: pyvespa - Release and upload PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.* # Run on tags like v1.2.3s (Tagged in pyvespa_bump_version.yml)

jobs:

  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]

      - name: Set version from ref tag that triggered the workflow (strip prefix 'v' from tag)
        id: set_version
        run: echo "version=${{ format('v{0}', github.ref_name) }}" >> $GITHUB_OUTPUT
      
      - name: Update version
        run: |
          echo "Updating pyvespa version to ${{ steps.set_version.outputs.version }}"
          python vespa/utils/update_version.py --version ${{ steps.set_version.outputs.version }}

      - name: Build
        run: |
          python -m build
      
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_PYVESPA }} #TODO: this must be added to secrets
        run: python -m twine upload dist/* 
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update pyvespa version to ${{ steps.set_version.outputs.version }}"
          title: "Update pyvespa version to ${{ steps.set_version.outputs.version }}"
          body: "This PR updates the pyvespa version to ${{ steps.set_version.outputs.version }}"
          branch: "update-pyvespa-version-${{ steps.set_version.outputs.version }}"
          base: "master"
          labels: "pyvespa"